FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install --assume-yes software-properties-common && \
  add-apt-repository ppa:hwangsaeul/ppa && \
  apt-get update && \
  apt-get install --assume-yes -t xenial-backports debhelper meson && \
  apt-get install --assume-yes libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
    libsrt-dev gstreamer1.0-plugins-good git \
    ca-certificates curl jq iputils-ping libcurl3 libicu55 python3-wheel

RUN mkdir -p /azp

WORKDIR /azp
COPY ./start.sh .
RUN chmod +x start.sh

CMD ["/azp/start.sh"]
