FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install --assume-yes software-properties-common && \
  add-apt-repository ppa:hwangsaeul/continuous-integration && \
  apt-get update && \
  apt-get install --assume-yes debhelper meson libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
    libsrt-dev \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    git \
    ca-certificates curl jq iputils-ping libcurl4 libicu60 python3-wheel \
    libjson-glib-dev librabbitmq-dev

RUN mkdir -p /azp

WORKDIR /azp
COPY ./start.sh .
RUN chmod +x start.sh

CMD ["/azp/start.sh"]
