FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install --assume-yes software-properties-common && \
  add-apt-repository ppa:hwangsaeul/continuous-integration && \
  apt-get update && \
  apt-get install --assume-yes -t xenial-backports debhelper meson && \
  apt-get install --assume-yes libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
    libsrt-dev \
    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    git sudo \
    ca-certificates curl jq iputils-ping libcurl3 libicu55 python3-wheel python3-pip \
    libjson-glib-dev librabbitmq-dev

RUN mkdir -p /azp

WORKDIR /azp
COPY ./start.sh .
RUN chmod +x start.sh

RUN locale-gen en_US.UTF-8 \
 && echo "LANG=\"en_US.UTF-8\"" > /etc/default/locale \
 && update-locale

RUN useradd ubuntu-builder -m -u 1000 && \
    echo "ubuntu-builder ALL=(ALL:ALL) NOPASSWD:ALL"   >> /etc/sudoers

USER ubuntu-builder
ENV PATH="/home/ubuntu-builder/.local/bin:${PATH}"

RUN git config --global user.email "noreply@hwangsaeul.org" \
 && git config --global user.name "No Reply"

CMD ["/azp/start.sh"]
